//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WALLET_SERVICE.Api {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WALLET_SERVICE.Api.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WALLET_SERVICE.Api.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WALLET_SERVICE.Api.
        /// </summary>
        public static string DocumentTitle {
            get {
                return ResourceManager.GetString("DocumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;div class=&apos;cont-sod wrapper&apos;&gt;&lt;div id=&apos;img-cont&apos;&gt;&lt;img src=&apos;https://cdn.prod.website-files.com/66041f2aa7176fac4965cba4/661840500e6036d571173b79_LogoPayphoneHorizontal.svg&apos; class=&apos;home_icon&apos; alt=&apos;Homecenter&apos;/&gt;&lt;/div&gt;    &lt;div item xs={10} class=&apos;title-display&apos;&gt;&lt;div class=&apos;title-head&apos;&gt;&lt;/div&gt;    &lt;/div&gt;  &lt;/div&gt; &lt;div class=&apos;subtitle-cont&apos; item xs={12}&gt;      &lt;div class=&apos;subtitle&apos;&gt;Juntos construimos sueños y proyectos de hogar&lt;/div&gt;   &lt;div class=&apos;subtitle-two&apos;&gt;&lt;/div&gt;  &lt;/div&gt;
        ///.
        /// </summary>
        public static string HeadContent {
            get {
                return ResourceManager.GetString("HeadContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WALLET_SERVICE.Api.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://www.payphone.app/.
        /// </summary>
        public static string UrlHome {
            get {
                return ResourceManager.GetString("UrlHome", resourceCulture);
            }
        }
    }
}
